require 'rake'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.pattern = 'test/*_test.rb'
  t.verbose = true
  t.warning = true
end

desc "Grab ACH institutions file and insert into sqlite DB"
task :go do
  puts "go"
end

#task :default => [:test_units]
